
set lines 200 pages 999;

select INDEX_STATS_ENABLED, INDEX_STATS_COLLECTION_TYPE, ACTIVE_ELEM_COUNT, LAST_FLUSH_TIME from v$index_usage_info;

SELECT u.*
FROM dba_index_usage u
JOIN user_indexes i ON u.owner = user AND u.name = i.index_name
order by i.table_name;

select OBJECT_ID, NAME, OWNER, TOTAL_ACCESS_COUNT, TOTAL_EXEC_COUNT, LAST_USED from dba_index_usage where owner=user;

select  NAME,TOTAL_ACCESS_COUNT,TOTAL_EXEC_COUNT,BUCKET_0_ACCESS_COUNT B0C,BUCKET_1_ACCESS_COUNT B1C,BUCKET_2_10_ACCESS_COUNT B2_10_C,BUCKET_2_10_ROWS_RETURNED B2_10_R,BUCKET_11_100_ACCESS_COUNT B11_100_C,BUCKET_11_100_ROWS_RETURNED B11_100_R,LAST_USED
from dba_index_usage where owner=user;


