col sid for 99999
col serial# for 99999
col OPNAME for a30
col SOFAR for 99999999
col TOTALWORK for 99999999
col COMPLETE for 999.00
col INST_ID for 99
col ELAPSED_TIME for a12
col TIME_REMAINING for a14
SELECT INST_ID, SID,       SERIAL#,
       opname,       SOFAR,
       TOTALWORK,       ROUND(SOFAR / TOTALWORK * 100, 2) COMPLETE,
       lpad(ROUND(ELAPSED_SECONDS/60) || ':' || MOD(ELAPSED_SECONDS,60), 12) ELAPSED_TIME,
       lpad(ROUND(TIME_REMAINING/60) || ':' || MOD(TIME_REMAINING,60), 14) TIME_REMAINING
  FROM GV$SESSION_LONGOPS
 WHERE TOTALWORK != 0
   AND SOFAR != TOTALWORK
 order by 1;

