set lines 120;
col PROPERTY_NAME for a50;
col value for a50;
SELECT PROPERTY_NAME, SUBSTR(property_value, 1, 30) value
FROM DATABASE_PROPERTIES
WHERE PROPERTY_NAME LIKE 'DST_%'ORDER BY PROPERTY_NAME;   
